# Generated by Django 4.0.6 on 2022-07-31 14:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0002_rename_teams_team'),
    ]

    operations = [
        migrations.RenameField(
            model_name='team',
            old_name='destignation',
            new_name='designation',
        ),
    ]
